### ISSUE TITLE
distutils deprecation

### ISSUE THREAD

**Issue by SuperSandro2000** [paulaltin/git-hires-merge#21]
When loading the script with python 3.11 I am granted with

```
/etc/profiles/per-user/sandro/bin/git-hires-merge:54: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.util import strtobool
```

There is no replacement for strtobool planned, so we would need to code something ourselves.

**Comment by Clindbergh** [comment]
Seems to be unavailable on current Mac OS:

```
/Users/primary/repos/intemp/gitlab/intemp/uniweb/uniweb-api/./git-hires-merge:330: SyntaxWarning: invalid escape sequence '\W'
  segments = re.split('(\W)', ln)
/Users/primary/repos/intemp/gitlab/intemp/uniweb/uniweb-api/./git-hires-merge:334: SyntaxWarning: invalid escape sequence '\W'
  segments = re.split('(\W)', ln)
Traceback (most recent call last):
  File "/Users/primary/repos/intemp/gitlab/intemp/uniweb/uniweb-api/./git-hires-merge", line 54, in <module>
    from distutils.util import strtobool
ModuleNotFoundError: No module named 'distutils'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/primary/repos/intemp/gitlab/intemp/uniweb/uniweb-api/./git-hires-merge", line 56, in <module>
    from distutils import strtobool
ModuleNotFoundError: No module named 'distutils'
```
